---
# purpose: Defaults for eveng_healthcheck
# maintainer: HybridOps.Studio

eveng_healthcheck_level: basic
eveng_healthcheck_fail_on_warning: false
eveng_healthcheck_report_format: summary

eveng_healthcheck_save_output: true
eveng_healthcheck_output_dir: >-
  {{ playbook_dir }}/outputs/artifacts/ansible/eveng_healthcheck
eveng_healthcheck_reports_dir: >-
  {{ playbook_dir }}/outputs/reports/ansible/eveng_healthcheck

eveng_healthcheck_services_enabled: true
eveng_healthcheck_database_enabled: true
eveng_healthcheck_api_enabled: true
eveng_healthcheck_virtualization_enabled: true
eveng_healthcheck_images_enabled: false
eveng_healthcheck_labs_enabled: false

eveng_healthcheck_admin_username: admin
eveng_healthcheck_admin_password: >-
  {{ lookup('ansible.builtin.env', 'EVENG_ADMIN_PASSWORD') | default('eve', true) }}
